site_name: Chinmaya Forms Framework
theme:
  name: 'material'
  features:
    - tabs
  palette:
    primary: white
    accent: deep purple
  logo: ./img/logo.png
  favicon: ./img/logo.png
  font:
    text: -apple-system, system-ui, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Ubuntu, Arial, sans-serif
    # code: Ubuntu Mono

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

extra_css:
  - main.css

repo_name: epicfaace/CFF
repo_url: https://github.com/epicfaace/CFF

nav:
  - Home: index.md
  - Form Management:
      Introduction: mgmt/forms-setup.md
      Managing responses: mgmt/responses.md
      Permissions and sharing: mgmt/share.md
  - Form Editing:
    - Introduction: editing/introduction.md
    - Schema:
        Introduction: schema/introduction.md
        Sample Schemas: schema/sample-schemas.md
    - uiSchema:
        Introduction: uischema/introduction.md
        Custom Fields:
          Auto Populate: uischema/fields/auto-populate.md
          Dynamic Enum: uischema/fields/dynamic-enum.md
          Same As: uischema/fields/same-as.md
          Address Autocomplete: uischema/fields/addressAutocompleteField.md
        Custom Widgets:
          Infobox Radio / Select: uischema/widgets/infoboxRadioWidget.md
        Custom Validation: uischema/validate.md
        Arrays: uischema/arrays.md
    - FormOptions:
        Introduction: formOptions/introduction.md
        Confirmation Emails:
          Introduction: payment/confirmation.md
          Sample templates: payment/confirmation-templates.md
          Jinja2 template reference: payment/confirmation-jinja.md
        Payment Integration:
          Introduction: payment/introduction.md
          Payment Expressions: payment/expressions.md
          Message Customization: payment/messages.md
          Payment Table: payment/payment-table.md
          Recurring Payments: payment/recurring.md
          Supported Payment Methods:
            Check Payments: payment/check.md
            CCAvenue: payment/ccavenue.md
          Currency: payment/currency.md
        Closing Submissions: formOptions/closing-submissions.md
        Response Counter: formOptions/counter.md
        Postprocess form data: formOptions/postprocess.md
        Import data with predicates: formOptions/predicates.md
        Configure response view with data options:
          Data Options: responses/data_options.md
          Create a dashboard: dashboard/dashboard_options.md
          Edit Schema: responses/edit_schema.md
        Omit Extra Data: formOptions/omitExtraData.md
  - Using the API:
      API Quickstart: api/api-quickstart.md
  - Development on CFF:
      Introduction: development/introduction.md
      Using Git and GitHub: development/git.md
      Backend setup notes: development/backend.md
