import os

MODE = os.getenv("MODE", "DEV")
USER_POOL_ID = os.getenv("USER_POOL_ID")
COGNITO_CLIENT_ID = os.getenv("COGNITO_CLIENT_ID")
S3_UPLOADS_BUCKET_NAME = os.getenv("S3_UPLOADS_BUCKET_NAME")
PROD = True if MODE == "PROD" else False

MONGO_CONN_STR = os.getenv("MONGO_CONN_STR")
SES_AWS_ACCESS_KEY_ID = os.getenv("SES_AWS_ACCESS_KEY_ID")
SES_AWS_SECRET_ACCESS_KEY = os.getenv("SES_AWS_SECRET_ACCESS_KEY")
SES_AWS_REGION = os.getenv("SES_AWS_REGION", "us-east-1")
